In [276]:
# Dependencies
import requests
import json
from config import api_key
from config import gkey
import census
from census import Census
import pandas as pd
import matplotlib.pyplot as plt
import us
from us import states


# Load Files

HH_Workforce2011_Raw_NN_data = "HH_Workforce2011_Raw_NN.csv"
HH_Workforce2012_Raw_NN_data = "HH_Workforce2012_Raw_NN.csv"
HH_Workforce2013_Raw_NN_data = "HH_Workforce2013_Raw_NN.csv"
HH_Workforce2014_Raw_NN_data = "HH_Workforce2014_Raw_NN.csv"
HH_Workforce2015_Raw_NN_data = "HH_Workforce2015_Raw_NN.csv"
HH_Workforce2016_Raw_NN_data = "HH_Workforce2016_Raw_NN.csv"
HH_Workforce2017_Raw_NN_data = "HH_Workforce2017_Raw_NN.csv"



# Read household_type data from 2011 to 2017
HH_Workforce2011_Clean_NN_data = pd.read_csv(HH_Workforce2011_Raw_NN_data)
HH_Workforce2012_Clean_NN_data = pd.read_csv(HH_Workforce2012_Raw_NN_data)
HH_Workforce2013_Clean_NN_data = pd.read_csv(HH_Workforce2013_Raw_NN_data)
HH_Workforce2014_Clean_NN_data = pd.read_csv(HH_Workforce2014_Raw_NN_data)
HH_Workforce2015_Clean_NN_data = pd.read_csv(HH_Workforce2015_Raw_NN_data)
HH_Workforce2016_Clean_NN_data = pd.read_csv(HH_Workforce2016_Raw_NN_data)
HH_Workforce2017_Clean_NN_data = pd.read_csv(HH_Workforce2017_Raw_NN_data)

# Display the data table for preview

HH_Workforce2017_Clean_NN_data=HH_Workforce2017_Clean_NN_data.drop([6,46,132,72])

HH_Workforce2017_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

#Save file
HH_Workforce2017_Clean_NN_data.to_csv('HH_Workforce2017_Clean_NN-EO.csv',index=False)

In [277]:
HH_Workforce2016_Clean_NN_data=HH_Workforce2016_Clean_NN_data.drop([98,124,11,47])

#HH_Workforce2016_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

HH_Workforce2016_Clean_NN_data.to_csv('HH_Workforce2016_Clean_NN-EO.csv',index=False)

HH_Workforce2016_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

,Zipcode,Total employed in civilian labor force,Aggregate travel time to work (in minutes)
3,77002,3433.0,60325.0
51,77050,2110.0,62465.0
131,77562,4143.0,96550.0
130,77547,4303.0,106225.0
31,77030,5831.0,115610.0
93,77094,4364.0,120560.0
4,77003,5584.0,128740.0
33,77032,4384.0,134725.0
52,77051,5194.0,135205.0
29,77028,5635.0,149965.0
96,77098,9296.0,159510.0
117,77484,5013.0,165645.0
77,77078,5837.0,172275.0
30,77029,6981.0,174950.0
28,77027,10332.0,176655.0
67,77068,6073.0,179560.0
111,77401,8925.0,186755.0
1,77587,7127.0,188745.0
12,77011,7595.0,191445.0
49,77048,6740.0,194835.0
55,77056,11630.0,197100.0
99,77336,5675.0,204885.0
58,77059,8532.0,211365.0
14,77013,8748.0,214295.0
57,77058,9722.0,223050.0
6,77005,13091.0,226505.0
84,77085,8345.0,235145.0
32,77031,9306.0,239000.0
20,77019,13668.0,240860.0
121,77504,10510.0,252825.0
...,...,...,...
126,77521,24368.0,565805.0
43,77042,23021.0,568955.0
72,77073,19863.0,569100.0
74,77075,19833.0,571680.0
101,77339,20630.0,607320.0
80,77081,23575.0,619225.0
16,77015,24232.0,625720.0
105,77375,21550.0,627710.0
97,77099,23352.0,643300.0
87,77088,23039.0,676940.0
108,77388,22618.0,692940.0
63,77064,24764.0,693285.0
41,77040,24786.0,699525.0
69,77070,26661.0,731270.0
110,77396,24320.0,740225.0
81,77082,28863.0,812990.0
88,77089,26461.0,825560.0
76,77077,31790.0,829260.0
71,77072,28669.0,843345.0
104,77373,28958.0,869490.0
103,77346,29814.0,947175.0
37,77036,35864.0,958075.0
116,77450,35673.0,1100610.0
82,77083,36118.0,1114940.0
113,77433,32113.0,1121405.0
94,77095,36831.0,1194570.0
107,77379,38735.0,1239410.0
112,77429,40644.0,1284675.0
83,77084,52857.0,1604535.0
115,77449,55736.0,1770860.0

In [278]:
HH_Workforce2015_Clean_NN_data=HH_Workforce2015_Clean_NN_data.drop([98,124,11,47])

#HH_Workforce2015_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

#Save file
HH_Workforce2015_Clean_NN_data.to_csv('HH_Workforce2015_Clean_NN-EO.csv',index=False)

HH_Workforce2015_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

,Zipcode,Total employed in civilian labor force,Aggregate travel time to work (in minutes)
3,77002,3433.0,60325.0
51,77050,2110.0,62465.0
131,77562,4143.0,96550.0
130,77547,4303.0,106225.0
31,77030,5831.0,115610.0
93,77094,4364.0,120560.0
4,77003,5584.0,128740.0
33,77032,4384.0,134725.0
52,77051,5194.0,135205.0
29,77028,5635.0,149965.0
96,77098,9296.0,159510.0
117,77484,5013.0,165645.0
77,77078,5837.0,172275.0
30,77029,6981.0,174950.0
28,77027,10332.0,176655.0
67,77068,6073.0,179560.0
111,77401,8925.0,186755.0
1,77587,7127.0,188745.0
12,77011,7595.0,191445.0
49,77048,6740.0,194835.0
55,77056,11630.0,197100.0
99,77336,5675.0,204885.0
58,77059,8532.0,211365.0
14,77013,8748.0,214295.0
57,77058,9722.0,223050.0
6,77005,13091.0,226505.0
84,77085,8345.0,235145.0
32,77031,9306.0,239000.0
20,77019,13668.0,240860.0
121,77504,10510.0,252825.0
...,...,...,...
126,77521,24368.0,565805.0
43,77042,23021.0,568955.0
72,77073,19863.0,569100.0
74,77075,19833.0,571680.0
101,77339,20630.0,607320.0
80,77081,23575.0,619225.0
16,77015,24232.0,625720.0
105,77375,21550.0,627710.0
97,77099,23352.0,643300.0
87,77088,23039.0,676940.0
108,77388,22618.0,692940.0
63,77064,24764.0,693285.0
41,77040,24786.0,699525.0
69,77070,26661.0,731270.0
110,77396,24320.0,740225.0
81,77082,28863.0,812990.0
88,77089,26461.0,825560.0
76,77077,31790.0,829260.0
71,77072,28669.0,843345.0
104,77373,28958.0,869490.0
103,77346,29814.0,947175.0
37,77036,35864.0,958075.0
116,77450,35673.0,1100610.0
82,77083,36118.0,1114940.0
113,77433,32113.0,1121405.0
94,77095,36831.0,1194570.0
107,77379,38735.0,1239410.0
112,77429,40644.0,1284675.0
83,77084,52857.0,1604535.0
115,77449,55736.0,1770860.0

In [279]:
HH_Workforce2014_Clean_NN_data=HH_Workforce2014_Clean_NN_data.drop([19,55,132,106])

#HH_Workforce2014_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

#save file
HH_Workforce2014_Clean_NN_data.to_csv('HH_Workforce2014_Clean_NN-EO.csv',index=False)

HH_Workforce2014_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

,Zipcode,Total employed in civilian labor force,Aggregate travel time to work (in minutes)
11,77002,3202.0,54940.0
59,77050,2172.0,58775.0
5,77547,3945.0,96300.0
39,77030,5979.0,107970.0
60,77051,4534.0,112700.0
41,77032,3972.0,113390.0
6,77562,4547.0,113805.0
101,77094,4295.0,117030.0
12,77003,5353.0,123730.0
37,77028,5443.0,141130.0
38,77029,6014.0,143065.0
75,77068,5585.0,150985.0
85,77078,5171.0,154415.0
9,77587,6848.0,167545.0
125,77484,5218.0,171575.0
119,77401,8854.0,172200.0
104,77098,9429.0,173085.0
107,77336,5136.0,178725.0
63,77056,10314.0,178970.0
57,77048,6467.0,180305.0
20,77011,7491.0,186985.0
36,77027,10708.0,189745.0
65,77058,9134.0,195680.0
14,77005,12592.0,200825.0
22,77013,8421.0,201290.0
92,77085,7321.0,213235.0
122,77447,5481.0,216070.0
40,77031,8620.0,217815.0
66,77059,9078.0,222415.0
28,77019,12987.0,226925.0
...,...,...,...
72,77065,20127.0,520590.0
80,77073,19101.0,538875.0
82,77075,19010.0,548465.0
87,77080,22969.0,548690.0
113,77375,18914.0,553555.0
88,77081,21442.0,557755.0
24,77015,23385.0,577965.0
109,77339,20876.0,592850.0
105,77099,21031.0,611610.0
95,77088,22055.0,622340.0
71,77064,23971.0,627580.0
116,77388,21068.0,643620.0
49,77040,24838.0,658950.0
118,77396,23173.0,686520.0
77,77070,25913.0,710605.0
96,77089,26464.0,772140.0
84,77077,30762.0,773725.0
89,77082,27720.0,778630.0
112,77373,27180.0,789040.0
79,77072,28144.0,800370.0
45,77036,33143.0,838335.0
111,77346,27933.0,857800.0
121,77433,27649.0,912300.0
90,77083,33835.0,1041115.0
124,77450,36234.0,1053330.0
115,77379,35873.0,1090460.0
120,77429,38749.0,1150250.0
102,77095,36986.0,1167445.0
123,77449,48205.0,1504830.0
91,77084,51040.0,1525830.0

In [285]:
HH_Workforce2013_Clean_NN_data=HH_Workforce2013_Clean_NN_data.drop([13,49,126,100])

#HH_Workforce2013_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')
#save file
HH_Workforce2013_Clean_NN_data.to_csv('HH_Workforce2013_Clean_NN-EO.csv',index=False)

HH_Workforce2013_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

KeyError: '[ 13  49 126 100] not found in axis'

In [289]:
HH_Workforce2012_Clean_NN_data=HH_Workforce2012_Clean_NN_data.drop([])

#HH_Workforce2012_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

#save file
HH_Workforce2012_Clean_NN_data.to_csv('HH_Workforce2012_Clean_NN-EO.csv',index=False)

HH_Workforce2012_Clean_NN_data.sort_values(by='Total employed in civilian labor force')

,Zipcode,Total employed in civilian labor force,Aggregate travel time to work (in minutes)
67,77050,1782.0,47465.0
13,77547,3701.0,87600.0
49,77032,3708.0,105170.0
109,77094,3986.0,103720.0
14,77562,4553.0,118655.0
68,77051,4569.0,108465.0
20,77003,4805.0,106035.0
0,77484,5259.0,174485.0
115,77336,5458.0,178450.0
93,77078,5475.0,175120.0
83,77068,5571.0,146120.0
130,77447,5686.0,209700.0
47,77030,6208.0,115720.0
45,77028,6218.0,182550.0
46,77029,6258.0,159990.0
65,77048,6264.0,180970.0
17,77587,6874.0,172890.0
28,77011,7212.0,181725.0
100,77085,7336.0,197535.0
43,77026,7481.0,237405.0
30,77013,7848.0,181425.0
54,77037,7920.0,218445.0
84,77069,8175.0,230465.0
112,77098,8742.0,161510.0
48,77031,8758.0,211800.0
127,77401,9077.0,158900.0
29,77012,9206.0,267545.0
74,77059,9411.0,227030.0
73,77058,9465.0,209020.0
106,77091,9484.0,242415.0
...,...,...,...
70,77055,20181.0,432925.0
124,77388,20384.0,595370.0
113,77099,20392.0,536875.0
59,77042,20437.0,499015.0
24,77007,20595.0,409175.0
9,77521,20597.0,468820.0
78,77063,21381.0,514230.0
103,77088,21390.0,606580.0
96,77081,21574.0,545590.0
57,77040,22843.0,591075.0
32,77015,22850.0,541330.0
79,77064,23018.0,590630.0
95,77080,23293.0,565240.0
72,77057,23717.0,515025.0
129,77433,23902.0,781220.0
85,77070,24861.0,668065.0
87,77072,25957.0,724080.0
104,77089,26570.0,714315.0
97,77082,26651.0,707675.0
119,77346,26951.0,818675.0
120,77373,27348.0,795130.0
92,77077,29101.0,722625.0
53,77036,31026.0,771260.0
98,77083,33405.0,1022275.0
132,77450,33751.0,961815.0
110,77095,35289.0,1156790.0
128,77429,36262.0,1091125.0
123,77379,36510.0,1083495.0
131,77449,42746.0,1371160.0
99,77084,50382.0,1505955.0

In [294]:
HH_Workforce2011_Clean_NN_data=HH_Workforce2011_Clean_NN_data.drop([8,44,95,121])

#HH_Workforce2011_Clean_NN_data.sort_values(by='Aggregate travel time to work (in minutes)')

#save file
HH_Workforce2011_Clean_NN_data.to_csv('HH_Workforce2011_Clean_NN-EO.csv',index=False)

HH_Workforce2011_Clean_NN_data.sort_values(by='Total employed in civilian labor force')

KeyError: '[  8  44  95 121] not found in axis'

In [295]:
#HH_Workforce2011_Clean_NN_data=HH_Workforce2011_Clean_NN_data.mean(axis=1)
#HH_Workforce2011_Clean_NN_data

# Add in Poverty Rate (Poverty Count / Population)
HH_Workforce2011_Clean_NN_data["Average_Travel_Time"]= HH_Workforce2011_Clean_NN_data["Aggregate travel time to work (in minutes)"].astype(int) / HH_Workforce2011_Clean_NN_data["Total employed in civilian labor force"].astype(int)
# Final DataFrame
HH_Workforce2011_Clean_NN_data = HH_Workforce2011_Clean_NN_data[["Zipcode", "Average_Travel_Time", "Total employed in civilian labor force","Aggregate travel time to work (in minutes)"]]

#this is to create a new column and add it to the current data

KeyError: 'Aggregate travel time to work (in minutes)'